default_platform(:ios)

xcodeproj_file="TLDExtractSwift.xcodeproj"
scheme = "TLDExtractSwift"

desc "Run all jobs"
lane :run_all do
    lint_swift
    tests
    build_spm
    build_carthage
    gen_docs
end

##########################################
# Versioning
##########################################

desc "Set version number"
lane :set_version do |options|
    current_app_version = get_version_number_from_xcodeproj(xcodeproj: xcodeproj_file)
    new_app_version = options[:version]&.to_s
    if new_app_version.nil? then
        unless UI.interactive? then
            UI.user_error!("No TTY to prompt on. Pass the version instead: fastlane set_version version:#{current_app_version}")
        end
        new_app_version = UI.input("Please enter version number (Current: #{current_app_version}): ")
    end
    # Anchored so that partial matches such as "1a2b3" are rejected
    unless new_app_version.match?(/\A\d+\.\d+\.\d+\z/) then
        UI.user_error!("Invalid version number. #{new_app_version}")
    end
    # Set version number to project
    increment_version_number_in_xcodeproj(version_number: new_app_version)
    UI.message("Changed version from #{current_app_version} to #{new_app_version} ")
end

desc "Bump version number"
lane :bump_version do |options|
    bump_types = ["patch", "minor", "major"]
    bump_type = options[:type]&.to_s
    if bump_type.nil? then
        unless UI.interactive? then
            UI.user_error!("No TTY to prompt on. Pass the bump type instead: fastlane bump_version type:patch")
        end
        bump_type = UI.select("Select version position to be upgraded: ", bump_types)
    end
    unless bump_types.include?(bump_type) then
        UI.user_error!("Invalid bump type. #{bump_type} (expected one of: #{bump_types.join(", ")})")
    end
    current_app_version = get_version_number_from_xcodeproj(xcodeproj: xcodeproj_file)
    current_app_versions = current_app_version.split(".")
    current_app_version_patch = current_app_versions[2].to_i
    current_app_version_minor = current_app_versions[1].to_i
    current_app_version_major = current_app_versions[0].to_i
    UI.message(current_app_versions)
    if bump_type == "patch" then
        current_app_version_patch += 1
    elsif bump_type == "minor" then
        current_app_version_patch = 0
        current_app_version_minor += 1
    elsif bump_type == "major" then
        current_app_version_patch = 0
        current_app_version_minor = 0
        current_app_version_major += 1
    end
    new_app_version = [current_app_version_major, current_app_version_minor, current_app_version_patch].join(".")
    # Set version number to project
    increment_version_number_in_xcodeproj(version_number: new_app_version)
    UI.message("Changed version from #{current_app_version} to #{new_app_version} ")
end

##########################################
# Lint
##########################################

desc "Lint codes with swift-format"
lane :lint_swift do
    # sh("swift-format", "format", "--in-place", "--ignore-unparsable-files", "--configuration", "../.swift-format", "--recursive", "../Sources", "../Tests")
    sh("swift-format", "lint", "--ignore-unparsable-files", "--configuration", "../.swift-format", "--recursive", "../Sources", "../Tests")
end

##########################################
# Test
##########################################

desc "Run all tests"
lane :tests do
    xcclean

    desc "Run macOS Tests"
    run_tests(
        destination: "platform=macOS",
        scheme: scheme,
        force_quit_simulator: true,
        reset_simulator: true,
        prelaunch_simulator: false,
        code_coverage: true,
        open_report: false,
        output_files: "report-macos.html,report-macos.junit"
    )
    slather(
        scheme: scheme,
        proj: xcodeproj_file,
        output_directory: "./fastlane/reports/macOS",
        html: true,
        show: false
    )

    desc "Run iOS Tests"
    run_tests(
        destination: "platform=iOS Simulator,name=iPhone 15 Pro",
        scheme: scheme,
        force_quit_simulator: true,
        reset_simulator: true,
        prelaunch_simulator: false,
        code_coverage: true,
        open_report: false,
        output_files: "report-ios.html,report-ios.junit"
    )
    slather(
        scheme: scheme,
        proj: xcodeproj_file,
        output_directory: "./fastlane/reports/iOS",
        html: true,
        show: false
    )

    desc "Run tvOS Tests"
    run_tests(
        destination: "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)",
        scheme: scheme,
        force_quit_simulator: true,
        reset_simulator: true,
        prelaunch_simulator: false,
        code_coverage: true,
        open_report: false,
        output_files: "report-tvos.html,report-tvos.junit"
    )
    slather(
        scheme: scheme,
        proj: xcodeproj_file,
        output_directory: "./fastlane/reports/tvOS",
        html: true,
        show: false
    )

    desc "Run watchOS Tests"
    run_tests(
        destination: "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)",
        scheme: scheme,
        force_quit_simulator: true,
        reset_simulator: true,
        prelaunch_simulator: false,
        code_coverage: true,
        open_report: false,
        output_files: "report-watchos.html,report-watchos.junit"
    )
    slather(
        scheme: scheme,
        proj: xcodeproj_file,
        output_directory: "./fastlane/reports/watchOS",
        html: true,
        show: false
    )

    desc "Run visionOS Tests"
    run_tests(
        destination: "platform=visionOS Simulator,name=Apple Vision Pro",
        scheme: scheme,
        force_quit_simulator: true,
        reset_simulator: true,
        prelaunch_simulator: false,
        code_coverage: true,
        open_report: false,
        output_files: "report-visionos.html,report-visionos.junit"
    )
    slather(
        scheme: scheme,
        proj: xcodeproj_file,
        output_directory: "./fastlane/reports/visionOS",
        html: true,
        show: false
    )

end

##########################################
# Package Manager
##########################################

desc "Lint Swift Package Manager"
lane :build_spm do |options|
    spm(
        command: "build",
        parallel: true
    )
    spm(
        command: "test",
        parallel: true
    )
end

desc "Build Carthage"
lane :build_carthage do |options|
    carthage(
        command: "build",
        verbose: false,
        platform: "Mac",
        # use_xcframeworks: true,
        no_skip_current: true
    )
    carthage(
        command: "build",
        verbose: false,
        platform: "iOS",
        use_xcframeworks: true,
        no_skip_current: true
    )
    carthage(
        command: "build",
        verbose: false,
        platform: "tvOS",
        use_xcframeworks: true,
        no_skip_current: true
    )
    carthage(
        command: "build",
        verbose: false,
        platform: "watchOS",
        use_xcframeworks: true,
        no_skip_current: true
    )
    # carthage(
    #     command: "build",
    #     verbose: false,
    #     platform: "visionOS",
    #     use_xcframeworks: true,
    #     no_skip_current: true
    # )
end

##########################################
# Swift Docs
##########################################

desc "Generate DocC documentation site into docc-site/"
lane :gen_docs do
    Dir.chdir("..") do
        sh("./scripts/gen_docs.sh")
    end
end